水钢6.6干部大会学习心得体会

2013年6月6日参加了水钢干部大会，会上总经理张新建同志作了题为《亡羊补牢守底线 卧薪尝胆求生存 万众一心 实事求是 向管理要效益的重要讲话》，张槐祥书记作了动员总结发言。
* 会议的内函及信息
** 会议主题
参加会议，让我子解到：
所谓“亡羊补牢”是因我们的管理“积淀隐藏的致命顽疾”，用对生产、设备统管变革、“查隐患、反违章、学三规四制、提素质”来弥补我们的管理漏洞。所谓“守住底线”，就是水钢当前的环境下能求得生存权，不被淘汰，要求通过挖潜，万众一心，实事求是，向管理要效益，全力以赴，从改变自我，历练自我，挑战自我，超越自我开始。战胜各种困难，实现最危险的2013年成功突，在取得钢铁行业生存权的底线上，积蓄出打赢生存战的能力和素质，凝练出赢得持久战的精神的文化。
** 当前形势
新建总经理总结到：
宏观上，钢铁企业正面对寒冬，生存空间狭小，正面临淘汰赛。必须思考的是我拿什么去求生存？
企业内部，事故频发，影响深远，暴露出深层次的基础管理问题，同时暴露了干部职工基本素质的停顿，不适应当前设备及生产工艺的要求。
** 会议交给的任务
*** 坚定不移地实施生产、设备统管变革。
一是有职有岗必照规范的责任唯一管理。每一名领导、干部、职工都必须对自己工作中的言行举止承担责任，兑现奖惩。
二是有规有制必循标准的准绳唯一管理。每一个岗位都必须对自己正常履职尽责的应知应会熟练掌握，对相邻的上下道工序基本规程、制度了然于胸，并将规章制度作为唯一准绳，精准作业。
三是有凭有据必遵原则的真实唯一管理。每一级管理者都必须对自己的上级和下级负责，时时事事以大局整体效益为中心，把空间留给公司，讲究凭据，账实相符，坚持原则，真实可控。
*** 全面开展“查隐患、反违章、学三规四制、提素质”活动。
会议要求，正确认识活动的目标任务，牢固树立全员参与意识，全面建立长效学习机制。
* 结合自身的岗位对今后工作的思考
作为设备管理岗位，会上通报的几起设备事故让我内心深受触动。结合工作实践，我的认识是，现代设备的特点是大型化、精密化、自动集成化，一但失去管控，造成事故，迫使生产中断，必将给企业造成重大损失。
** 要撑控住设备，首先是要了解设备的自身特点，会正确使用和维护，通过点检避免发生意外，通过劣化分析完成定修及更换。这些，通过学习和实践设备的“三规”可提高员工和撑控能力。
** 设备“三规”需要不断的学习和完善，所以应推动各项设备管理规程的学习和完善工作，这是设备管理岗位长期持续研究的重点内容之一。
** 设备管理是全员参与的管理，操作、点检、维修到管理者必须有明确的任务和责任，并规范实施。








