#+Author: 蒋登平
#+Title:  现代人十二种不良思维习惯
#+OPTIONS: html-postamble:auto html-preamble:t tex:t
#+CREATOR: <a href="http://www.gnu.org/software/emacs/">Emacs</a> 24.3.50.3 (<a href="http://orgmode.org">Org</a> mode 8.0.3)
#+HTML_CONTAINER: div
#+HTML_DOCTYPE: xhtml-strict
#+HTML_HEAD:xf
#+HTML_HEAD_EXTRA:
#+HTML_HTML5_FANCY:
#+HTML_INCLUDE_SCRIPTS:
#+HTML_INCLUDE_STYLE:
#+HTML_LINK_HOME:
#+HTML_LINK_UP:
#+HTML_MATHJAX:
#+INFOJS_OPT:
* 在智力方面
** 直线思维。即所谓顺竿爬、给个棒槌就纫针的思维方式。人一旦用这种思维方式思考问题， 说话和做事很容易出现两种倾向：一种是钻牛角尖，一种是不得要领。直线思维俗话也叫不转弯、一根筋、少根弦、幼雅病。所以，这样的人易上当、应变能力较差，缺乏幽默感和想象力，很难与他人进行有效交流和良好的沟通，更谈不上有人与人之间和谐默契感。解决直线思维的有效方法，就是多多进行发散思维训练，彻底改变自己原有的思考方式。

发散思维：又称为辐射思维、扩散思维、求异思维，是在思维过程中，以某一问题为中心，沿着不同方向、不同角度、向外扩散和一种思维方式。

** 固化思维。也你思维定势，俗话叫死心眼、老脑壳、顽固不化或一条道走到黑。特点是在认识事物的过程中，往往不分青红皂白，以一事而类推其它。人在家庭、事业中出现以偏概全、片面判断和认识问题的现象，其根源就在于某些这种固化思维习惯。解决固化思维的有效方法，就是要养成站在对方立场上和多角度思考问题的习惯。

* 在性格方面
** 猜忌思维。俗称小心眼、毛毛虫，猜忌思维是与某些人的性格特征紧紧捆绑在一起的。这种思维方式源于某些人的多疑、忧虑、抑郁、恐惧和对周围人缺乏信任的心理现象。一旦形成习惯，会给生活和处世带来很大的心理压力，产生不安、狂躁、歇斯底里等不好情绪。解决猜忌思维的有效途径是自我脱敏疗法，即进行自我安慰，养成凡事顺其自然的心理习惯，也就是放下包袱、轻松上阵。

** 排异思维。排异思维俗称概不论，也有人称有此思维习惯的人的行为表现为匪气。有这种思维习惯的人表现为平时做事特立独行、标新立异，做事不考虑行为后果，一切皆由我行我素、刚愎自用，对他人意见不分好坏，皆持逆反或否定心理。这样的人倾听能力较差，注重主观判断而不善于客观分析，或封闭而盲目自大，或善交而虚荣排他。解决排异思维的有效方法是学会倾听他人意见，在家庭和工作中讲民主，学会当听众，天长日久就能改变这种不良思维习惯。

** 利己思维。俗称铁公鸡、小气鬼。有利己思维习惯的人考虑问题时，一切从个人角度如个人观点、需要、爱好等出发，不顾他人感受甚至哗众取宠。这样的人有很强的领地意识和索取意识，平时爱占小便宜，嫉妒心强，关键时候欲壑难填，即便对待自己的家人和要好的朋友，也是不见兔子不撒鹰、以己为重。改变利己思维的有效方法，就是学会与人公平交往，养成做事大度、肯干奉献的好习惯。

** 领导思维。领导思维亦称专断思维或权力思维，俗称拍脑壳、拍胸脯、我说算，也叫好当头儿，是封建制度遗存下来的一种统治思想。持有这种思维的人或多或少具有扭曲性格，往往自觉不自觉地以一种居高临下的态度看待周围的人，他们用这种态度维护自己的自尊和虚荣，置他人于服从地位。这样的人有的脾气暴躁做事不计后果，有的表面温和却深藏权欲，往往对家庭和社会成员造成极大的心理伤害。改变领导思维的有效方法，是学会端正心态、找准定位，即学会营造其成员间的民主和谐氛围，加强个人民主意识，将自己置于正常的普通人地位。

* 在生存能力方面
** 惰性思维。也叫懒汉思维，俗称随大流。有人把惰性思维和固化思维等同起来，实际上它们是有区别的。固化思维是指死心眼，惰性思维则是指没心眼，即社会上广泛存在的从众心理，习惯惰性思维的人，不善于以判断、分析、归纳等思维方法认识周围的人和事，而是一味求同、随大流，人云亦云、人做我做。解决惰性思维的有效方法是，进行求异思维训练，养成用正确的思维方法进行思考的好习惯。

** 被动思维。被动思维与主动思维正相反，是缘于惰性思维的一种思维习惯。被动思维俗称慢半拍，主要表现为平时不好思考，事后瞎着急。解决被动思维的有效方法，就是说话和做事前要有计划、要做好充分准备，过程中要注意观察、调整，事后要有总结和反思。

** 盲目思维。盲目思维俗称瞎琢磨。盲目思维在人类诞生的那一天起，人类就拥有了它，在人类初期，它帮了人类的忙，人类成就以后，它就成了人类的一种不良思维习惯。这种源于人类独有的幻想心理的不良习惯让人思维散漫，思考不专一而且缺乏系统性，逻辑性。主要表现为，讲话时如车轴，浮想联翩却摸不着主题；做事时东一锤西一镐，想到哪干到哪毫无边际。解决盲目思维的有效方法是，养成想一事做一事成一事、一事一做的习惯。

* 在生活态度方面
** 侥幸思维。侥幸思维俗称碰运气或彩票心理。持这种思维习惯的人做事不讲究方式方法，既无远大目标也不会精细打算，总抱着当一天和尚撞一天钟、直到哪看到哪的消极想法，在机会面前容易出现丟西瓜捡芝麻现象。民间有书到用时方恨少或心比天高、命比纸薄的说法，就是对这些人的生动写照。解决侥幸思维的有效方法，就是养成做事脚踏实地的习惯。

** 中庸思维。中庸思维亦称毛驴思维，是一种落后的思维习惯。有这种思维习惯的人很明显的性格表现，就是做事不求甚解，说话左右逢源而没有主见。他们做事时或找借口或自嘲，总是满足于他人的脸色和自己的虚荣为出发点，采取不伤人也不伤己的态度，表面上对他人的事情漠不关心，而将自己的目的深埋于心。民间有气有笑无、比上不足比下有余的说法，就是对这种思维习惯的概括。中庸思维是一种假性思维，因为中庸态度仅是一种表面态度，本质上则反映了这种思维的刻薄性和对他人的敌视性。人的贪欲、无奈和悲观态度是产生中庸思维的温床。改变中庸思维的有效方法，是树立积极乐观的人生观和良好的生活态度。

** 迷信思维。也叫突变思维，俗称脑子进水，既是相对于信任思维而产生的一种畸形思维习惯，也是和利己思维、排异思维相伴而生的一种最复杂的不良思维习惯。虽然迷信思维主要反映了一个人的生活态度，但与性格形成却有很大关系。有这种思维习惯和人个人意识极强，一般有两种行为倾向：一是固执己见、心胸狭隘，俗称小肚鸡肠；二是偏听偏信，不辨是非，俗称玩世不恭。青少年中存在的盲目崇拜现象，也属于迷信思维的一种表现。小肚鸡肠的人对待他人评价极为敏感，喜欢奉承他人（即拍马屁）也喜欢他人奉承自己（即座轿子），做事好跟风而动（即墙头草、见风使舵）还会好大喜功干出劳民伤财之事（俗称出风头），玩世不恭的人喜好逃避社会责任（俗称混混儿），为人好拉帮结派亦好挑起内讧（俗称狗脸、浑虫），喜欢模仿或通过他人来实现个人的目的。迷信思维导致的生活态度对集体和社会具有极大的危害性，而且这样的人权力越大对人和社会的危害越大。改变迷信思维的有效方法是，注意完善个人性格修养，端正人生观念，提高对他人和社会的责任意识。
